//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:2.0.50727.5485
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS58Listen.PrintService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintService.OrderDataSoap")]
    public interface OrderDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void InsertOrder(string order, string usid, string desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string getAllOrder(string usid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrderItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void getOrderItem(string OrderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPrintOrderData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataSet getPrintOrderData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePrintFlag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        void UpdatePrintFlag(string OrderNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OrderDataSoapChannel : POS58Listen.PrintService.OrderDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrderDataSoapClient : System.ServiceModel.ClientBase<POS58Listen.PrintService.OrderDataSoap>, POS58Listen.PrintService.OrderDataSoap {
        
        public OrderDataSoapClient() {
        }
        
        public OrderDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public void InsertOrder(string order, string usid, string desc) {
            base.Channel.InsertOrder(order, usid, desc);
        }
        
        public string getAllOrder(string usid) {
            return base.Channel.getAllOrder(usid);
        }
        
        public void getOrderItem(string OrderNo) {
            base.Channel.getOrderItem(OrderNo);
        }
        
        public System.Data.DataSet getPrintOrderData() {
            return base.Channel.getPrintOrderData();
        }
        
        public void UpdatePrintFlag(string OrderNo) {
            base.Channel.UpdatePrintFlag(OrderNo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintService.OrderDataHttpGet")]
    public interface OrderDataHttpGet {
        
        // CODEGEN: 作業 HelloWorld 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/HelloWorldRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.HelloWorldResponse HelloWorld(POS58Listen.PrintService.HelloWorldRequest request);
        
        // CODEGEN: 作業 InsertOrder 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/InsertOrderRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/InsertOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.InsertOrderResponse InsertOrder(POS58Listen.PrintService.InsertOrderRequest request);
        
        // CODEGEN: 作業 getAllOrder 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/getAllOrderRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/getAllOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getAllOrderResponse getAllOrder(POS58Listen.PrintService.getAllOrderRequest request);
        
        // CODEGEN: 作業 getOrderItem 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/getOrderItemRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/getOrderItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getOrderItemResponse getOrderItem(POS58Listen.PrintService.getOrderItemRequest request);
        
        // CODEGEN: 作業 getPrintOrderData 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/getPrintOrderDataRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/getPrintOrderDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getPrintOrderDataResponse getPrintOrderData(POS58Listen.PrintService.getPrintOrderDataRequest request);
        
        // CODEGEN: 作業 UpdatePrintFlag 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpGet/UpdatePrintFlagRequest", ReplyAction="http://tempuri.org/OrderDataHttpGet/UpdatePrintFlagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.UpdatePrintFlagResponse UpdatePrintFlag(POS58Listen.PrintService.UpdatePrintFlagRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string usid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string desc;
        
        public InsertOrderRequest() {
        }
        
        public InsertOrderRequest(string order, string usid, string desc) {
            this.order = order;
            this.usid = usid;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderResponse {
        
        public InsertOrderResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usid;
        
        public getAllOrderRequest() {
        }
        
        public getAllOrderRequest(string usid) {
            this.usid = usid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getAllOrderResponse() {
        }
        
        public getAllOrderResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OrderNo;
        
        public getOrderItemRequest() {
        }
        
        public getOrderItemRequest(string OrderNo) {
            this.OrderNo = OrderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderItemResponse {
        
        public getOrderItemResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrintOrderDataRequest {
        
        public getPrintOrderDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrintOrderDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getPrintOrderDataResponse() {
        }
        
        public getPrintOrderDataResponse(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrintFlagRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OrderNo;
        
        public UpdatePrintFlagRequest() {
        }
        
        public UpdatePrintFlagRequest(string OrderNo) {
            this.OrderNo = OrderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrintFlagResponse {
        
        public UpdatePrintFlagResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OrderDataHttpGetChannel : POS58Listen.PrintService.OrderDataHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrderDataHttpGetClient : System.ServiceModel.ClientBase<POS58Listen.PrintService.OrderDataHttpGet>, POS58Listen.PrintService.OrderDataHttpGet {
        
        public OrderDataHttpGetClient() {
        }
        
        public OrderDataHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderDataHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.HelloWorldResponse POS58Listen.PrintService.OrderDataHttpGet.HelloWorld(POS58Listen.PrintService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            POS58Listen.PrintService.HelloWorldRequest inValue = new POS58Listen.PrintService.HelloWorldRequest();
            POS58Listen.PrintService.HelloWorldResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).HelloWorld(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.InsertOrderResponse POS58Listen.PrintService.OrderDataHttpGet.InsertOrder(POS58Listen.PrintService.InsertOrderRequest request) {
            return base.Channel.InsertOrder(request);
        }
        
        public void InsertOrder(string order, string usid, string desc) {
            POS58Listen.PrintService.InsertOrderRequest inValue = new POS58Listen.PrintService.InsertOrderRequest();
            inValue.order = order;
            inValue.usid = usid;
            inValue.desc = desc;
            POS58Listen.PrintService.InsertOrderResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).InsertOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getAllOrderResponse POS58Listen.PrintService.OrderDataHttpGet.getAllOrder(POS58Listen.PrintService.getAllOrderRequest request) {
            return base.Channel.getAllOrder(request);
        }
        
        public string getAllOrder(string usid) {
            POS58Listen.PrintService.getAllOrderRequest inValue = new POS58Listen.PrintService.getAllOrderRequest();
            inValue.usid = usid;
            POS58Listen.PrintService.getAllOrderResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).getAllOrder(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getOrderItemResponse POS58Listen.PrintService.OrderDataHttpGet.getOrderItem(POS58Listen.PrintService.getOrderItemRequest request) {
            return base.Channel.getOrderItem(request);
        }
        
        public void getOrderItem(string OrderNo) {
            POS58Listen.PrintService.getOrderItemRequest inValue = new POS58Listen.PrintService.getOrderItemRequest();
            inValue.OrderNo = OrderNo;
            POS58Listen.PrintService.getOrderItemResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).getOrderItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getPrintOrderDataResponse POS58Listen.PrintService.OrderDataHttpGet.getPrintOrderData(POS58Listen.PrintService.getPrintOrderDataRequest request) {
            return base.Channel.getPrintOrderData(request);
        }
        
        public System.Data.DataSet getPrintOrderData() {
            POS58Listen.PrintService.getPrintOrderDataRequest inValue = new POS58Listen.PrintService.getPrintOrderDataRequest();
            POS58Listen.PrintService.getPrintOrderDataResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).getPrintOrderData(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.UpdatePrintFlagResponse POS58Listen.PrintService.OrderDataHttpGet.UpdatePrintFlag(POS58Listen.PrintService.UpdatePrintFlagRequest request) {
            return base.Channel.UpdatePrintFlag(request);
        }
        
        public void UpdatePrintFlag(string OrderNo) {
            POS58Listen.PrintService.UpdatePrintFlagRequest inValue = new POS58Listen.PrintService.UpdatePrintFlagRequest();
            inValue.OrderNo = OrderNo;
            POS58Listen.PrintService.UpdatePrintFlagResponse retVal = ((POS58Listen.PrintService.OrderDataHttpGet)(this)).UpdatePrintFlag(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintService.OrderDataHttpPost")]
    public interface OrderDataHttpPost {
        
        // CODEGEN: 作業 HelloWorld 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/HelloWorldRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.HelloWorldResponse1 HelloWorld(POS58Listen.PrintService.HelloWorldRequest1 request);
        
        // CODEGEN: 作業 InsertOrder 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/InsertOrderRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/InsertOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.InsertOrderResponse1 InsertOrder(POS58Listen.PrintService.InsertOrderRequest1 request);
        
        // CODEGEN: 作業 getAllOrder 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/getAllOrderRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/getAllOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getAllOrderResponse1 getAllOrder(POS58Listen.PrintService.getAllOrderRequest1 request);
        
        // CODEGEN: 作業 getOrderItem 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/getOrderItemRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/getOrderItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getOrderItemResponse1 getOrderItem(POS58Listen.PrintService.getOrderItemRequest1 request);
        
        // CODEGEN: 作業 getPrintOrderData 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/getPrintOrderDataRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/getPrintOrderDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.getPrintOrderDataResponse1 getPrintOrderData(POS58Listen.PrintService.getPrintOrderDataRequest1 request);
        
        // CODEGEN: 作業 UpdatePrintFlag 未由 RPC 或文件所包裝，正在產生訊息合約。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderDataHttpPost/UpdatePrintFlagRequest", ReplyAction="http://tempuri.org/OrderDataHttpPost/UpdatePrintFlagResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        POS58Listen.PrintService.UpdatePrintFlagResponse1 UpdatePrintFlag(POS58Listen.PrintService.UpdatePrintFlagRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest1 {
        
        public HelloWorldRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorldResponse1() {
        }
        
        public HelloWorldResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string order;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string usid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string desc;
        
        public InsertOrderRequest1() {
        }
        
        public InsertOrderRequest1(string order, string usid, string desc) {
            this.order = order;
            this.usid = usid;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertOrderResponse1 {
        
        public InsertOrderResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllOrderRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usid;
        
        public getAllOrderRequest1() {
        }
        
        public getAllOrderRequest1(string usid) {
            this.usid = usid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllOrderResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public getAllOrderResponse1() {
        }
        
        public getAllOrderResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderItemRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OrderNo;
        
        public getOrderItemRequest1() {
        }
        
        public getOrderItemRequest1(string OrderNo) {
            this.OrderNo = OrderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderItemResponse1 {
        
        public getOrderItemResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrintOrderDataRequest1 {
        
        public getPrintOrderDataRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPrintOrderDataResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataSet DataSet;
        
        public getPrintOrderDataResponse1() {
        }
        
        public getPrintOrderDataResponse1(System.Data.DataSet DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrintFlagRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OrderNo;
        
        public UpdatePrintFlagRequest1() {
        }
        
        public UpdatePrintFlagRequest1(string OrderNo) {
            this.OrderNo = OrderNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePrintFlagResponse1 {
        
        public UpdatePrintFlagResponse1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface OrderDataHttpPostChannel : POS58Listen.PrintService.OrderDataHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class OrderDataHttpPostClient : System.ServiceModel.ClientBase<POS58Listen.PrintService.OrderDataHttpPost>, POS58Listen.PrintService.OrderDataHttpPost {
        
        public OrderDataHttpPostClient() {
        }
        
        public OrderDataHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderDataHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDataHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.HelloWorldResponse1 POS58Listen.PrintService.OrderDataHttpPost.HelloWorld(POS58Listen.PrintService.HelloWorldRequest1 request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            POS58Listen.PrintService.HelloWorldRequest1 inValue = new POS58Listen.PrintService.HelloWorldRequest1();
            POS58Listen.PrintService.HelloWorldResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).HelloWorld(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.InsertOrderResponse1 POS58Listen.PrintService.OrderDataHttpPost.InsertOrder(POS58Listen.PrintService.InsertOrderRequest1 request) {
            return base.Channel.InsertOrder(request);
        }
        
        public void InsertOrder(string order, string usid, string desc) {
            POS58Listen.PrintService.InsertOrderRequest1 inValue = new POS58Listen.PrintService.InsertOrderRequest1();
            inValue.order = order;
            inValue.usid = usid;
            inValue.desc = desc;
            POS58Listen.PrintService.InsertOrderResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).InsertOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getAllOrderResponse1 POS58Listen.PrintService.OrderDataHttpPost.getAllOrder(POS58Listen.PrintService.getAllOrderRequest1 request) {
            return base.Channel.getAllOrder(request);
        }
        
        public string getAllOrder(string usid) {
            POS58Listen.PrintService.getAllOrderRequest1 inValue = new POS58Listen.PrintService.getAllOrderRequest1();
            inValue.usid = usid;
            POS58Listen.PrintService.getAllOrderResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).getAllOrder(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getOrderItemResponse1 POS58Listen.PrintService.OrderDataHttpPost.getOrderItem(POS58Listen.PrintService.getOrderItemRequest1 request) {
            return base.Channel.getOrderItem(request);
        }
        
        public void getOrderItem(string OrderNo) {
            POS58Listen.PrintService.getOrderItemRequest1 inValue = new POS58Listen.PrintService.getOrderItemRequest1();
            inValue.OrderNo = OrderNo;
            POS58Listen.PrintService.getOrderItemResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).getOrderItem(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.getPrintOrderDataResponse1 POS58Listen.PrintService.OrderDataHttpPost.getPrintOrderData(POS58Listen.PrintService.getPrintOrderDataRequest1 request) {
            return base.Channel.getPrintOrderData(request);
        }
        
        public System.Data.DataSet getPrintOrderData() {
            POS58Listen.PrintService.getPrintOrderDataRequest1 inValue = new POS58Listen.PrintService.getPrintOrderDataRequest1();
            POS58Listen.PrintService.getPrintOrderDataResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).getPrintOrderData(inValue);
            return retVal.DataSet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS58Listen.PrintService.UpdatePrintFlagResponse1 POS58Listen.PrintService.OrderDataHttpPost.UpdatePrintFlag(POS58Listen.PrintService.UpdatePrintFlagRequest1 request) {
            return base.Channel.UpdatePrintFlag(request);
        }
        
        public void UpdatePrintFlag(string OrderNo) {
            POS58Listen.PrintService.UpdatePrintFlagRequest1 inValue = new POS58Listen.PrintService.UpdatePrintFlagRequest1();
            inValue.OrderNo = OrderNo;
            POS58Listen.PrintService.UpdatePrintFlagResponse1 retVal = ((POS58Listen.PrintService.OrderDataHttpPost)(this)).UpdatePrintFlag(inValue);
        }
    }
}
